config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'goods#index'

  resources :users, only: [:index, :show, :edit, :update]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

    
  resources :goods do
    resources :likes, only: [:create, :destroy]

    resources :comments, only: [:create, :destroy]


  end

end


Rails.application.routes.draw do
  resources :goods
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


         has_many :relationships
         has_many :followings, through: :relationships, source: :follow
         has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
         has_many :followers, through: :reverse_of_relationships, source: :user

        has_many :goods, dependent: :destroy

        has_many :likes, dependent: :destroy
        has_many :liked_goods, through: :likes, source: :good

        has_many :comments, dependent: :destroy

        devise :database_authenticatable, :registerable,
                :recoverable, :rememberable, :trackable, :validatable
        has_many :messages, dependent: :destroy
        has_many :entries, dependent: :destroy

        has_many :goods, dependent: :destroy
        validates :username, presence: true
        validates :profile, length: { maximum: 200 }

        
        mount_uploader :image, ImageUploader
        mount_uploader :avatar, AvatarUploader

        def follow(other_user)
          unless self == other_user
            self.relationships.find_or_create_by(follow_id: other_user.id)
          end
        end
      
        def unfollow(other_user)
          relationship = self.relationships.find_by(follow_id: other_user.id)
          relationship.destroy if relationship
        end
      
        def following?(other_user)
          self.followings.include?(other_user)
        end
        
        def already_liked?(good)
          self.likes.exists?(good_id: good.id)
        end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  
  def index
    @users=User.all
    @goods = @user.goods.group_by_month(:created_at).count
  end


  def update
    if @user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def follows
    user = User.find(params[:id])
    @users = user.following_users
  end
  
  def followers
    user = User.find(params[:id])
    @user = user.follower_users
  end
  


  def show
    @user = User.find(params[:id])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
      @msg ="他のユーザーとDMしてみよう！"
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12">
        <br>
        <br>
            <h1>DMサンプル</h1>
            <h2>User一覧ページ</h2>

            <% if user_signed_in? %>
                <h2><%= current_user.email %>でログインしています</h2> 
                <br>

                <%= button_to "SignOut", destroy_user_session_path, :method => :delete, class:"signOutButton" %>
            <br>
            <br>
        </div>
        <div class="col-md-6">
                    <% number = 1%>
                    <div class="flex">
                        <% @users.each do |u| %>
                        <div class="user-in">
                            <p>プロフィール No.<%= number %></p>
                            <p><%= u.email %>さん</p>
                            <p><%= link_to 'ユーザーページへ', user_path(u.id) %></p>
                        </div>
                        <% number += 1 %>
                        <% end %>
                    </div>

            <% else %>
            <%= link_to "SignUp", new_user_registration_path %>
            <br>
            <%= link_to "SignIn", new_user_session_path %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<br>
<br>
<h1><p class="text-center">Profile</p></h1>

<div class="content">
  <div class="box1">
    <%= image_tag @user.image_url, size: "250x200" if @user.image? %>
    <%= image_tag @user.avatar_url, size: "250x200" if @user.avatar? %>
  </div>

  <div class="p1">名前 : <%= @user.username %></p1>
  <div class="p2">メールアドレス : <%= @user.email %></p2>
  <div class="p3">プロフィール : <%= @user.profile %></p3>

  

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>


<div class="user-in">
  <h2><%= @user.email %></h2>

  <% if @user.id == current_user.id %>
      <%= @msg %>
  <% else %>
      <% if @isRoom == true %>
          <p><%= link_to 'DMへ', room_path(@roomId) %></p>
      <% else %>
          <%= form_for @room do |f| %>
              <%= fields_for @entry do |e|%>
                  <% e.hidden_field :user_id, value: @user.id %>
              <% end %>
          <%= f.submit "DMを開始する"%>
          <% end %>
      <% end %>
  <% end %>
</div>

<%= link_to "ユーザー一覧に戻る", users_path %>


<h2>ユーザーの投稿一覧</h2>
<% @user.goods.each do |g| %>
  <%= g.user.username %>
  <%= g.name %>
  <%= g.about %>

<% end %>


<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_goods.each do |g| %>
  <%= g.user.username %>
  <%= g.name %>
  <%= g.about %>
  
<% end %>


<%= link_to "投稿一覧に戻る", goods_path %>