config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'goods#index'

  resources :users, only: [:index, :show, :edit, :update]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

    
  resources :goods do
    resources :likes, only: [:create, :destroy]

    resources :comments, only: [:create, :destroy]


  end

end


Rails.application.routes.draw do
  resources :goods
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :good
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/good.rb
class Good < ApplicationRecord

    mount_uploader :image, ImageUploader

    belongs_to :user

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :good
  belongs_to :user

  validates_uniqueness_of :good_id, scope: :user_id

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


         has_many :relationships
         has_many :followings, through: :relationships, source: :follow
         has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
         has_many :followers, through: :reverse_of_relationships, source: :user

        has_many :goods, dependent: :destroy

        has_many :likes, dependent: :destroy
        has_many :liked_goods, through: :likes, source: :good

        has_many :comments, dependent: :destroy

        devise :database_authenticatable, :registerable,
                :recoverable, :rememberable, :trackable, :validatable
        has_many :messages, dependent: :destroy
        has_many :entries, dependent: :destroy

        has_many :goods, dependent: :destroy
        validates :username, presence: true
        validates :profile, length: { maximum: 200 }

        
        mount_uploader :image, ImageUploader
        mount_uploader :avatar, AvatarUploader

        def follow(other_user)
          unless self == other_user
            self.relationships.find_or_create_by(follow_id: other_user.id)
          end
        end
      
        def unfollow(other_user)
          relationship = self.relationships.find_by(follow_id: other_user.id)
          relationship.destroy if relationship
        end
      
        def following?(other_user)
          self.followings.include?(other_user)
        end
        
        def already_liked?(good)
          self.likes.exists?(good_id: good.id)
        end

end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
    before_action :authenticate_user!

    def index

        if params[:search] == nil
            @goods= Good.all
          elsif params[:search] == ''
            @goods= Good.all
          else
            #部分検索
            @goods = Good.where("name LIKE ? ",'%' + params[:search] + '%')
        end
    end

def new
    @good = Good.new
end

def create
    good = Good.new(good_params)

    good.user_id = current_user.id

    if good.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
end

def destroy
    good = Good.find(params[:id])
    good.destroy
    redirect_to action: :index
  end

def show
    @good = Good.find(params[:id])

    @comments = @good.comments
    @comment = Comment.new

end

def edit
    @good = Good.find(params[:id])
  end

def update
    good = Good.find(params[:id])
    if good.update(good_params)
      redirect_to :action => "show", :id => good.id
    else
      redirect_to :action => "new"
    end
end

  private
  def good_params
    params.require(:good).permit(:name, :about, :image)
  end

end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
      like = current_user.likes.create(good_id: params[:good_id]) 
      redirect_back(fallback_location: root_path)
    end
    
    def destroy
      like = Like.find_by(good_id: params[:good_id], user_id: current_user.id)
      like.destroy
      redirect_back(fallback_location: root_path)
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    before_action :authenticate_user!

  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
      @myUserId = current_user.id
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  
  def index
    @users=User.all
    @goods = @user.goods.group_by_month(:created_at).count
  end


  def update
    if @user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def follows
    user = User.find(params[:id])
    @users = user.following_users
  end
  
  def followers
    user = User.find(params[:id])
    @user = user.follower_users
  end
  


  def show
    @user = User.find(params[:id])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
      @msg ="他のユーザーとDMしてみよう！"
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goods/edit.html.erb
<div class="edit-container">
    <%= form_for @good do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, :size => 30 %> 
      <%= f.label :about %>
      <%= f.text_area :about, :size => "30x2" %> 
      <%= f.submit "編集する" %>
    <% end %>
</div>

<div class="edit-sub">
  <%= link_to "投稿一覧に戻る", goods_path %>
</div>

app/views/goods/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>
<div class="example">
    <img src="/assets/eiga.jpg" class="d-block w-100" alt="...">
    <p>最高の映画体験を。</p>
</div>

<%= line_chart @goods.group_by_day(:created_at).count%>


<br>
<br>
<h2><p class="text-center">Movie file</p></h2>

<div class="container">
    <div class="row">  
        <div class="col-md-9">
            <br>
            <br>
                <%= form_tag({controller:"goods",action:"index"}, method: :get) do %>
                    <%= text_field_tag :search %>
                    <br>
                    <br>
                    <button type="submit_tag" class="btn btn-outline-warning">Search</button>
                <% end %>
        </div>
        
        <div class="col-md-3">


            <%= button_to 'Logout', destroy_user_session_path, method: :delete %>
                <% if user_signed_in? %>
                    <%= link_to "My page", user_path(current_user.id) %>
                <% end %>

                <%= link_to "New post", new_good_path %>

        </div>
    </div>

<br>
<br>
<br>
<br>
                

        <div class="row">
           
            <% @goods.each do |g| %>
                
                <div class="col-4">
                    <div class="card" style="width: 18rem;">
                        <div class="card-body">
                            <div class="column flex-direction:row"> 
                                <%= image_tag g.image_url, size: "250x200" if g.image? %>
                                <br>
                                <br>
                                
                                        <% if user_signed_in? %>
                                        
                                            <% if current_user.already_liked?(g) %>
                                                <%= button_to good_like_path(id: g.id, good_id: g.id), method: :delete do %>
                                                    <i class="fa-solid fa-heart" style="color: red;"></i><%= g.likes.count %>
                                                <% end %>
                                            <% else %>
                                                <%= button_to good_likes_path(id: g.id, good_id: g.id), method: :post do %>
                                                    <i class="fa-regular fa-heart" style="color: gray;" ></i><%= g.likes.count %>
                                                <% end %>
                                            <% end %>   
                                        <% else %>
                                        <i class="far fa-heart"></i><%= g.likes.count %>
                                    <% end %>

                                    
                                    
                                        <h5 class="card-title"><%= link_to g.user.username, user_path(g.user.id) %></h5>
                                        <p class="card-text">
                                            <%= g.user.email %> 
                                            <br>
                                            <%= g.name %>
                                            <br>
                                            <%= g.about %>
                                            <br>
                                            <%= g.created_at %>
                                            <br>
                                        
                                
                                            <% if user_signed_in? && current_user.id == g.user_id %>
                                            <%= link_to "詳細", good_path(g.id) %>
                                            <%= link_to "編集する", edit_good_path(g.id) %>
                                            <%= button_to "削除する", good_path(g.id), method: :delete %>
                                        </p>
                            </div>            
                        </div>
                        
                    </div>
                    <br>
                    <br>

                        
                </div>
            <% end %>
            <% end %>
        </div>
    <div class="row"></div>
</div>
<br>
<br>
<br>
<div class="scroll-infinity">
      <div class="scroll-infinity__wrap">
        <ul class="scroll-infinity__list scroll-infinity__list--right">
          <li class="scroll-infinity__item"><img src="../assets/konan.jpg"></li>
          <li class="scroll-infinity__item"><img src="../assets/king.jpg"></li>
          <li class="scroll-infinity__item"><img src="../assets/bosei.jpg"></li>
          <li class="scroll-infinity__item"><img src="../assets/desny.jpg"></li>
          <li class="scroll-infinity__item"><img src="../assets/kisei.png"></li>
          <li class="scroll-infinity__item"><img src="../assets/lalaland.jpg"></li>
        </ul>
        <ul class="scroll-infinity__list scroll-infinity__list--right">
          <li class="scroll-infinity__item"><img src="../assets/kimi.jpg"></li>
          <li class="scroll-infinity__item"><img src="../assets/haken.jpg"></li>
          <li class="scroll-infinity__item"><img src="../assets/1200.jpg"></li>
          <li class="scroll-infinity__item"><img src="../assets/sigatu.jpg"></li>
          <li class="scroll-infinity__item"><img src="../assets/kujira.jpg"></li>
          <li class="scroll-infinity__item"><img src="../assets/tokyo.jpg"></li>
        </ul>
      </div>
      </div>
    

app/views/goods/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>

<div class="post-container">
<p class="title">New post</p>
<%= form_for @good do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, :size => 30 %>


    <%= f.label :about  %>
    <%= f.text_area :about, :size => "30x2" %>


 
    <%= f.label :image %>
    <%= f.file_field :image %>
 

  <%= f.submit "Post" %>
<% end %>
</div>

<div class="post-sub">
  <%= link_to "Go to post list", goods_path %>
</div>

app/views/goods/show.html.erb
<div class="goods-container">
<h3>投稿詳細</h3>
  <div class="good">
  
    <p><%= @good.name %></p>
    <p><%= @good.about %></p>
    <p><%= @good.user.email %></p>
    <p><%= @good.created_at %></p>


    <% if user_signed_in? %>
          <% if current_user.already_liked?(@good) %>
              <%= button_to good_like_path(@good), method: :delete do %>
                  <i class="fas fa-heart"></i><%= @good.likes.count %>
              <% end %>
          <% else %>
              <%= button_to good_likes_path(@good), method: :post do %>
                  <i class="far fa-heart"></i><%= @good.likes.count %>
              <% end %>
          <% end %>
          <% else %>
          <i class="far fa-heart"></i><%= @good.likes.count %>
          <% end %>
      <%= link_to "編集する", edit_good_path(@good.id) %>
  </div>

  <div class="show-sub">
    <h2>いいねしたユーザー</h2>
    <% @good.liked_users.each do |user| %>
      <li><%= user.email %></li>
    <% end %>
  </div>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
    <% if user_signed_in? && current_user.id == c.user_id %>
        <%= button_to "削除する", good_comment_path(c.id), method: :delete %>
    <% end %>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@good, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
  
</div>

<%= link_to "投稿一覧に戻る", goods_path %>

app/views/rooms/show.html.erb
<div class="user-in">
<% @entries.each do |e| %>
    <h3><strong><a href="/users/<%= e.user.id %>"><%= e.user.email%></a></strong></h3>
<% end %>
<p>2人のDM❤️</p>
</div>

<div class="dmMain">
    <% @messages.each do |m| %>
        <strong><%= m.body %></strong>
        <small><%= m.user.email %>さん</small><hr>
    <% end %>

    <%= form_for @message do |f| %>
    <%= f.text_field :body, :placeholder => "メッセージを入力して下さい" , :size => 100 %>
    <%= f.hidden_field :room_id, :value => @room.id %>
    <br>
    <%= f.submit "送信する" %>
    <% end %>
</div>

<%= link_to "ユーザー一覧に戻る", users_path %>